# Common configuration template for EasyShop services
spring:
  application:
    name: CHANGE-ME-SERVICE-NAME
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://config-server:8888}
  cloud:
    config:
      username: ${CONFIG_SERVER_USER:}
      password: ${CONFIG_SERVER_PASSWORD:}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

# Service-specific configuration (will be overridden by Config Server)
server:
  port: CHANGE-ME-PORT
