server: { port: ${SERVER_PORT:9003} }
spring:
  application: { name: order-service }
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa: { "hibernate": { "ddl-auto": "validate" }, "properties": { "hibernate": { "dialect": "org.hibernate.dialect.PostgreSQLDialect" } } }
  flyway: { "enabled": true,"locations": "classpath:db/migration","schemas": "easyshop","create-schemas": true }
jwt: { "secret": "${JWT_SECRET}","ttlMinutes": ${JWT_TTL_MINUTES:60} }
product:
  base-url: ${PRODUCT_BASE_URL}

logging:
  pattern:
    level: "%5p [trace:%X{traceId}]"

