server:
  port: 9001
spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA:auth}
jwt:
  secret: ${JWT_SECRET}
  ttlMinutes: ${JWT_TTL_MINUTES:60}
logging:
  pattern:
    level: "%5p [trace:%X{traceId}]"
