server:
  port: 9001
spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA:auth}
  security:
    oauth2:
      authorization-server:
        issuer: ${AUTH_SERVER_ISSUER:http://auth-service:9001}
        jwk-set-uri: ${AUTH_SERVER_ISSUER:http://auth-service:9001}/oauth2/jwks
        oidc:
          discovery-endpoint: ${AUTH_SERVER_ISSUER:http://auth-service:9001}/.well-known/openid-configuration
logging:
  pattern:
    level: "%5p [trace:%X{traceId}]"
