server:
  port: ${SERVER_PORT}
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa: { "hibernate": { "ddl-auto": "validate" }, "properties": { "hibernate": { "dialect": "org.hibernate.dialect.PostgreSQLDialect" } } }
  flyway: { "enabled": true,"locations": "classpath:db/migration","schemas": "easyshop","create-schemas": true }
jwt: { "secret": "${JWT_SECRET}","ttlMinutes": ${JWT_TTL_MINUTES} }

logging:
  pattern:
    level: "%5p [trace:%X{traceId}]"

