spring:
  application:
    name: purchase-service
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    config:
      username: ${CONFIG_SERVER_USER:}
      password: ${CONFIG_SERVER_PASSWORD:}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

# Service-specific configuration (will be overridden by Config Server)
server:
  port: 9003
