server:
  port: 9003
spring:
  application:
    name: purchase-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA:purchases}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_ISSUER:http://localhost:9001}
      client:
        registration:
          purchase-service:
            client-id: purchase-service
            client-secret: ${PURCHASE_SERVICE_CLIENT_SECRET:purchase-service-secret}
            authorization-grant-type: client_credentials
            scope: read,write
        provider:
          easyshop:
            issuer-uri: ${AUTH_SERVER_ISSUER:http://localhost:9001}
product:
  service:
    url: ${PRODUCT_SERVICE_URL:http://product-service:9002}
logging:
  pattern:
    level: "%5p [trace:%X{traceId}]"
