server:
  port: 9001

spring:
  application:
    name: auth-service
  security:
    oauth2:
      authorization-server:
        issuer: ${AUTH_SERVER_ISSUER}
        jwk-set-uri: ${AUTH_SERVER_ISSUER}/oauth2/jwks
        oidc:
          discovery-endpoint: ${AUTH_SERVER_ISSUER}/.well-known/openid-configuration
oauth2:
  clients:
    webapp:
      client-id: ${WEBAPP_CLIENT_ID}
      client-secret: ${WEBAPP_CLIENT_SECRET}
      redirect-uri: ${WEBAPP_REDIRECT_URI}
      scope: ${WEBAPP_SCOPE}
      authorization-grant-types: authorization_code,refresh_token
    gateway:
      client-id: ${GATEWAY_CLIENT_ID}
      client-secret: ${GATEWAY_CLIENT_SECRET}
      scope: ${GATEWAY_SCOPE}
      authorization-grant-types: client_credentials
    purchase-service:
      client-id: ${PURCHASE_SERVICE_CLIENT_ID}
      client-secret: ${PURCHASE_SERVICE_CLIENT_SECRET}
      scope: ${PURCHASE_SERVICE_SCOPE}
      authorization-grant-types: client_credentials

db:
  schema: ${database.schemas.auth}

