# Production environment configuration
spring:
  profiles:
    active: prod

logging:
  level:
    com.easyshop: WARN
    org.springframework.security: ERROR
    org.springframework.web: WARN
    org.springframework.cloud.config: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

oauth2:
  clients:
    webapp:
      client-id: ${WEBAPP_CLIENT_ID}
      client-secret: ${WEBAPP_CLIENT_SECRET}
      redirect-uri: ${WEBAPP_REDIRECT_URI}
      scope: ${WEBAPP_SCOPE}
    gateway:
      client-id: ${GATEWAY_CLIENT_ID}
      client-secret: ${GATEWAY_CLIENT_SECRET}
    purchase-service:
      client-id: ${PURCHASE_SERVICE_CLIENT_ID}
      client-secret: ${PURCHASE_SERVICE_CLIENT_SECRET}

security:
  require-ssl: ${REQUIRE_SSL}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
    allowed-methods: ${CORS_ALLOWED_METHODS}
    allowed-headers: ${CORS_ALLOWED_HEADERS}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS}
