# Common configuration for all environments
spring:
  application:
    name: easyshop
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        default_schema: ${DB_SCHEMA}
  flyway:
    url: ${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    default-schema: ${DB_SCHEMA}
    schemas: ${DB_SCHEMA}
    create-schemas: true
    table: flyway_schema_history
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_ISSUER}

# Service URLs
services:
  auth:
    url: ${AUTH_SERVICE_URL}
    issuer: ${AUTH_SERVER_ISSUER}
  product:
    url: ${PRODUCT_SERVICE_URL}
  purchase:
    url: ${PURCHASE_SERVICE_URL}
  api-gateway:
    url: ${API_GATEWAY_URL}

# API Routes configuration
routes:
  auth: ${AUTH_ROUTE}
  products: ${PRODUCTS_ROUTE}
  purchases: ${PURCHASES_ROUTE}

# Database Configuration
database:
  schemas:
    auth: ${AUTH_SCHEMA}
    products: ${PRODUCTS_SCHEMA}
    purchases: ${PURCHASES_SCHEMA}

# Logging Configuration
logging:
  pattern:
    level: "%5p [trace:%X{traceId}]"
  level:
    com.easyshop: INFO
    org.springframework.security: WARN
    org.springframework.web: INFO
