# Common configuration for all environments
spring:
  application:
    name: easyshop
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_ISSUER}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  ttl-minutes: ${JWT_TTL_MINUTES}

# Service URLs
services:
  auth:
    url: ${AUTH_SERVICE_URL}
    issuer: ${AUTH_SERVER_ISSUER}
  product:
    url: ${PRODUCT_SERVICE_URL}
  purchase:
    url: ${PURCHASE_SERVICE_URL}
  api-gateway:
    url: ${API_GATEWAY_URL}

# API Routes configuration
routes:
  auth: ${AUTH_ROUTE}
  products: ${PRODUCTS_ROUTE}
  purchases: ${PURCHASES_ROUTE}

# Database Configuration
database:
  url: ${DB_URL}
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  schemas:
    auth: ${AUTH_SCHEMA}
    products: ${PRODUCTS_SCHEMA}
    purchases: ${PURCHASES_SCHEMA}

# Logging Configuration
logging:
  pattern:
    level: "%5p [trace:%X{traceId}]"
  level:
    com.easyshop: INFO
    org.springframework.security: WARN
    org.springframework.web: INFO

