# Auth Service specific configuration
server:
  port: 9001

spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA}
  security:
    oauth2:
      authorization-server:
        issuer: ${AUTH_SERVER_ISSUER}
        jwk-set-uri: ${AUTH_SERVER_ISSUER}/oauth2/jwks
        oidc:
          discovery-endpoint: ${AUTH_SERVER_ISSUER}/.well-known/openid-configuration

# Flyway configuration
spring:
  flyway:
    schemas: ${SPRING_FLYWAY_SCHEMAS}
    default-schema: ${SPRING_FLYWAY_DEFAULT_SCHEMA}
    create-schemas: ${SPRING_FLYWAY_CREATE_SCHEMAS}
    table: ${SPRING_FLYWAY_TABLE}

# JWT configuration
jwt:
  secret: ${JWT_SECRET}
  ttl-minutes: ${JWT_TTL_MINUTES}

# OAuth2 clients configuration
oauth2:
  clients:
    webapp:
      client-id: ${WEBAPP_CLIENT_ID}
      client-secret: ${WEBAPP_CLIENT_SECRET}
      redirect-uri: ${WEBAPP_REDIRECT_URI}
      scope: ${WEBAPP_SCOPE}
      authorization-grant-types: authorization_code,refresh_token
    gateway:
      client-id: ${GATEWAY_CLIENT_ID}
      client-secret: ${GATEWAY_CLIENT_SECRET}
      scope: ${GATEWAY_SCOPE}
      authorization-grant-types: client_credentials
    purchase-service:
      client-id: ${PURCHASE_SERVICE_CLIENT_ID}
      client-secret: ${PURCHASE_SERVICE_CLIENT_SECRET}
      scope: ${PURCHASE_SERVICE_SCOPE}
      authorization-grant-types: client_credentials

