# Product Service specific configuration
server:
  port: 9002

spring:
  application:
    name: product-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_ISSUER}

# Product service specific settings
product:
  service:
    name: product-service
    version: ${SERVICE_VERSION}
    description: ${SERVICE_DESCRIPTION}

DB_SCHEMA: ${database.schemas.products}

