# Test environment configuration
spring:
  profiles:
    active: test
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        default_schema: ${DB_SCHEMA}

# Service URLs for test environment
services:
  auth:
    url: ${AUTH_SERVICE_URL}
    issuer: ${AUTH_SERVER_ISSUER}
  product:
    url: ${PRODUCT_SERVICE_URL}
  purchase:
    url: ${PURCHASE_SERVICE_URL}
  api-gateway:
    url: ${API_GATEWAY_URL}

# API Routes for test environment
routes:
  auth: ${AUTH_ROUTE}
  products: ${PRODUCTS_ROUTE}
  purchases: ${PURCHASES_ROUTE}

# Frontend configuration for test environment
frontend:
  url: ${FRONTEND_URL}
  api-base: ${API_BASE}
  auth-server-url: ${AUTH_SERVER_URL}

# Database schemas for test environment
database:
  schemas:
    auth: ${AUTH_SCHEMA}
    products: ${PRODUCTS_SCHEMA}
    purchases: ${PURCHASES_SCHEMA}

# Logging for test environment
logging:
  level:
    com.easyshop: INFO
    org.springframework.security: WARN
    org.springframework.web: INFO
    org.springframework.cloud.config: INFO

# OAuth2 configuration for test environment
oauth2:
  clients:
    webapp:
      client-id: ${WEBAPP_CLIENT_ID}
      client-secret: ${WEBAPP_CLIENT_SECRET}
      redirect-uri: ${WEBAPP_REDIRECT_URI}
      scope: ${WEBAPP_SCOPE}
    gateway:
      client-id: ${GATEWAY_CLIENT_ID}
      client-secret: ${GATEWAY_CLIENT_SECRET}
    purchase-service:
      client-id: ${PURCHASE_SERVICE_CLIENT_ID}
      client-secret: ${PURCHASE_SERVICE_CLIENT_SECRET}

