spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://config-server:8888
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

# Service-specific configuration (will be overridden by Config Server)
server:
  port: 8080
