server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://auth-service:9001
          predicates:
            - Path=/api/auth/**
        - id: orders
          uri: http://order-service:9002
          predicates:
            - Path=/api/orders/**
        - id: products
          uri: http://product-service:9003
          predicates:
            - Path=/api/products/**
logging:
  pattern:
    level: "%5p [trace:%X{traceId}]"