server: { port: ${SERVER_PORT:8080} }
spring:
  application: { name: api-gateway }
  cloud:
    gateway:
      routes:
        - id: auth
          uri: ${AUTH_URL}
          predicates: [ Path=/api/auth/**, /healthz, /readyz ]
        - id: products
          uri: ${PRODUCT_URL}
          predicates: [ Path=/api/products/** ]
        - id: orders
          uri: ${ORDER_URL}
          predicates: [ Path=/api/orders/** ]

logging:
  pattern:
    level: "%5p [trace:%X{traceId}]"
          