# Purchase Service specific configuration
server:
  port: 9003

spring:
  application:
    name: purchase-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_ISSUER}
      client:
        registration:
          purchase-service:
            client-id: ${PURCHASE_SERVICE_CLIENT_ID}
            client-secret: ${PURCHASE_SERVICE_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: ${PURCHASE_SERVICE_SCOPE}
        provider:
          easyshop:
            issuer-uri: ${AUTH_SERVER_ISSUER}

# Product service integration
product:
  service:
    url: ${PRODUCT_SERVICE_URL}

# Purchase service specific settings
purchase:
  service:
    name: purchase-service
    version: ${SERVICE_VERSION}
    description: ${SERVICE_DESCRIPTION}

db:
  schema: ${database.schemas.purchases}

