version: "3.9"

services:
  frontend:
    build: ../../frontend
    ports:
      - "80:80"
    depends_on:
      - api-gateway

  api-gateway:
    build: ../../backend/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - order-service
      - product-service

  auth-service:
    build: ../../backend/auth-service
    ports:
      - "8081:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}

  order-service:
    build: ../../backend/order-service
    ports:
      - "8082:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}

  product-service:
    build: ../../backend/product-service
    ports:
      - "8083:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=easyshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
