name: Backend Tests

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-tests.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Deploy common-security
        run: mvn -B -f backend/common-security/pom.xml deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test auth service
        run: mvn -B -f backend/auth-service/pom.xml test
      - name: Test product service
        run: mvn -B -f backend/product-service/pom.xml test
      - name: Test order service
        run: mvn -B -f backend/order-service/pom.xml test
      - name: Test API gateway
        run: mvn -B -f backend/api-gateway/pom.xml test
